
--DROP TABLE [ROLES];

--Crée la table ROLES
CREATE TABLE [ROLES](	
	[ROLE] [NVARCHAR](50) NOT NULL, 
	[IS_ADMIN] int NOT NULL ,
	PRIMARY KEY ([ROLE],[IS_ADMIN]));
	

INSERT INTO [ROLES] ([ROLE],[IS_ADMIN]) VALUES ('ROLE_USER',0);
INSERT INTO [ROLES] ([ROLE],[IS_ADMIN]) VALUES ('ROLE_ADMIN',1);