server.port: 8080
#Connection to DB
spring:
  profiles.active: secrets
  messages:
    encoding: UTF-8
  web:
    locale: en
  datasource:
    url: jdbc:sqlserver://localhost;databasename=BD_TROCENCHERES;integratedSecurity=false;encrypt=true;trustServerCertificate=true
#Options to DB
  jpa:
    properties:
      hibernate:
        open-in-view: true
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update